name: Terraform plan
on:
    push:
        branches:
        - main
    workflow_dispatch:

jobs:
    terraform_plan:
        name: Terraform plan
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 1.5.7

        - name: Open tunnel to Proxmox VE API
          run: bash "./.github/workflows/scripts/open-tunnel-to-proxmox.sh"
          env:
            CLOUDFLARE_TUNNEL_ID: ${{ secrets.CLOUDFLARE_TUNNEL_ID }}
            CLOUDFLARE_TUNNEL_SECRET: ${{ secrets.CLOUDFLARE_TUNNEL_SECRET }}

        - run: terraform init
          working-directory: "./terraform"

        - name: Terraform Plan
          working-directory: "./terraform"
          run: terraform plan -input=false -no-color
          env:
            TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
            TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}
